### ISSUE TITLE
Rectangle添加IsDragMoveArea=True后，窗体最大化之后无法拖动

### ISSUE THREAD

**Issue by DamianRice** [PanuonGroup/Panuon.WPF.UI#103]
<Rectangle Grid.Row="0" Fill="Transparent" pu:WindowX.IsDragMoveArea="True"/>

**Comment by Mochengvia** [comment]
是否在Rectangle上设置了Fill="Transparent" ？它的默认值为Null。

**Comment by Mochengvia** [comment]
如果仍有问题，请重新打开此issue。
