### ISSUE TITLE
ListBoxItemHelper.Icon能否放在最右侧 而不是Content的后面

### ISSUE THREAD

**Issue by Hakoyu** [PanuonGroup/Panuon.WPF.UI#104]
`ListBoxItemHelper.Icon`能否放在最右侧
`IconPlacement.Right`只会让它排列在`Content`的后面
可以的话希望添加一个`HorizontalContentAlignment`属性

**Comment by Mochengvia** [comment]
经过测试，在ListBox上使用HorizontalContentAlignment="Stretch"可以满足需要。
如果仍有问题，请重新打开此issue。
