### ISSUE TITLE
所有附加属性的Hover颜色 必须是实际值,不能是静态资源或者动态资源

### ISSUE THREAD

**Issue by yangf85** [PanuonGroup/Panuon.WPF.UI#109]
只有实际值 比如red green 才能显示 ,资源无法显示

**Comment by Mochengvia** [comment]
根据我的实际使用，你说的情况应当是由其他问题导致的。
如果使用静态资源，确保你的资源字典已经在 App.xaml 中引用，建议放在MergedResources中的最顶端。
如果使用动态资源，此问题不应当出现。请尝试在代码中使用FindResource方法检查是否能找到资源。
