### ISSUE TITLE
Can't use checkboxes

### ISSUE THREAD

**Issue by nidahoxto** [PanuonGroup/Panuon.WPF.UI#116]
`Unexpected token 'M 2,33333333333333,7,16666666666667 L6,10,6666666666667 L11,6666666666667,2,5`

It seems that the CheckBox Style Glyph has wrong Formatted data?

**Comment by Mochengvia** [comment]
What language does your development environment use?
There seems to have been feedback a long time ago that in a Spanish context (maybe Arabic? I can't remember) there would be a sign conversion anomaly that would cause this problem.

**Comment by Mochengvia** [comment]
In these cases, spaces in the text are converted to commas, causing this problem. I don't quite know the rules of these languages; maybe google can help you.
If there is a way to improve it, please leave me a message.
