### ISSUE TITLE
添加对Awesome Icon的支持

### ISSUE THREAD

**Issue by akchiji888** [PanuonGroup/Panuon.WPF.UI#122]
如题，不然Panuon自带的Icon相比起Awesome Icon库来说，可用的还是太少了

**Comment by Mochengvia** [comment]
事实上，pu是出于多样化的考虑才取消了对AwesomeIcon的支持。更多的用户喜欢使用IconFont等网站制作自己的个性化图标库，因此在项目中额外引用第三方的字体是不够明智的。
另外，我个人认为，AwesomeIcon的设计风格已经不再属于这个时代。

你可以将AwesomeIcon的ttf文件加入到项目资源文件中，然后参考文档和示例中 pu:GlobalSettings 的方法替换默认的图标字体，然后再所有的位置使用图标字体。

**Comment by jiushi97** [comment]
<FontFamily x:Key="font">pack://application:,,,/Resources/#Source Han Sans CN,/Panuon.WPF.UI;component/Resources/Fonts/#PanuonIcon,pack://application:,,,/Resources/#Font Awesome 6 Free Solid</FontFamily> 然后TextElement和TextBlock 引用就可以了

**Comment by akchiji888** [comment]
ok
