### ISSUE TITLE
ListView使用GridView时ItemsHorizontalAlignment丢失设置样式

### ISSUE THREAD

**Issue by SmRiley** [PanuonGroup/Panuon.WPF.UI#129]
pu.listViewHelper不存在ItemsHorizontalAlignment，所以只能使用LiteViewItemStyle设置这个居中，但是使用后会造成pu.ListViewHelper设置的样式丢失，变为原生样式

**Comment by Mochengvia** [comment]
此问题将在1.1.10.1中解决。
注意，在使用 `HorizontalContentAlignment="Center"` 时，还需要设置 `pu:ListViewHelper.ItemsPadding="0"` 。
