### ISSUE TITLE
WindowsX设置顶部背景颜色后最大化窗体时留有空隙无法填充满

### ISSUE THREAD

**Issue by luchong0813** [PanuonGroup/Panuon.WPF.UI#132]
![image](https://user-images.githubusercontent.com/46243214/217401200-0bb13d9f-307c-4826-a5b3-6f7cc1778c0c.png)

**Comment by luchong0813** [comment]
目前复现在Windows11上

**Comment by ZF-Follower** [comment]
windowx 模板里面有个这个东西我屏蔽了就好了
<Trigger Property="WindowState"
                     Value="Maximized">
                <Setter TargetName="GrdMain"
                        Property="Margin"
                        Value="8" />
            </Trigger>
@Mochengvia  这个是干嘛的呢？

**Comment by Mochengvia** [comment]
@ZF-Follower 
在Windows10及以下的版本中，窗体最大化会向内偏移8个像素点，这是一个历史问题，Windows11中解决了这个问题，所以导致11和10中显示效果不同
这个问题已经记录，会在下个版本修复

**Comment by Mochengvia** [comment]
@luchong0813 @ZF-Follower 在最新的Windows11版本中，这个问题似乎已经消失。有人能测试一下吗？

**Comment by Mochengvia** [comment]
更新到Windows11 22H2 22621.1265版本后，无法再次复现这个问题.
