### ISSUE TITLE
GroupBox设置HeaderBackground后，圆角会被遮挡住一部分，且Header没有margin属性

### ISSUE THREAD

**Issue by MisakaCirno** [PanuonGroup/Panuon.WPF.UI#135]

**Comment by Mochengvia** [comment]
感谢你的反馈。
1. 此问题已经确认。在之后的版本中，我会尽可能想办法解决它。
2. GroupBox确实没有HeaderMargin属性，但你可以通过HeaderHeight和HeaderPadding属性来调整标题内容的内边距。

如果有其他问题，请在此issue下留言。

**Comment by Mochengvia** [comment]
此问题已经修复，将在最近的版本中发布。
