### ISSUE TITLE
在PendingBoxSettings.CancelButtonStyle使用StaticResource时提示无法序列化非公共类型

### ISSUE THREAD

**Issue by Hakoyu** [PanuonGroup/Panuon.WPF.UI#147]
以下方法在`MessageBoxXSettings`中适用,但在`PendingBoxSettings`中无法使用
```xaml
<pu:PendingBoxSettings
  x:Key="pendingSettings"
  CancelButtonStyle="{StaticResource ButtonBaseStyle}">
</pu:PendingBoxSettings>
```
```xaml
<pu:PendingBoxSettings.ContentTemplate>
  <DataTemplate>
    <Grid>
      ...
      <Button
        x:Name="PART_CancelButton"
        Grid.Row="3"
        Margin="0,5,0,0"
        Style="{StaticResource ButtonBaseStyle}"
        HorizontalAlignment="Center"
        Visibility="Collapsed" />
    </Grid>
  </DataTemplate>
</pu:PendingBoxSettings.ContentTemplate>
```
```xaml
<pu:PendingBoxSettings.CancelButtonStyle>
  <Style BasedOn="{StaticResource ButtonBaseStyle}" TargetType="Button" />
</pu:PendingBoxSettings.CancelButtonStyle>
```
----
完整错误信息
```log
System.InvalidOperationException
  HResult=0x80131509
  Message=无法序列化非公共类型“Panuon.WPF.UI.Internal.Converters.IsNonnullConverter”。
  Source=PresentationFramework
  StackTrace:
   在 System.Windows.Markup.Primitives.MarkupWriter.VerifyTypeIsSerializable(Type type)
   在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)
   在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)
   在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)
   在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)
   在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)
   在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)
   在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)
   在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)
   在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)
   在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)
   在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)
   在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item)
   在 System.Windows.Markup.Primitives.MarkupWriter.SaveAsXml(XmlWriter writer, MarkupObject item)
   在 System.Windows.Markup.Primitives.MarkupWriter.SaveAsXml(XmlWriter writer, Object instance, XamlDesignerSerializationManager manager)
   在 System.Windows.Markup.XamlWriter.Save(Object obj, XamlDesignerSerializationManager manager)
   在 Panuon.WPF.UI.Internal.Utils.XamlUtil.ToXaml[T](T obj)
   在 Panuon.WPF.UI.PendingBox.<>c__DisplayClass21_0.<CallPendingBox>b__0()
   在 System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   在 Panuon.WPF.UI.PendingBox.Show(String message)
   在 StarsectorTools.Views.MainWindow.MainWindow.<Button_TitleMin_Click>d__18.MoveNext() 在 
   StarsectorTools\Views\MainWindow\MainWindow.xaml.cs 中: 第 81 行
```

**Comment by Hakoyu** [comment]
根据
https://github.com/PanuonGroup/Panuon.WPF.UI/blob/c0f29c207daf39cb141363442bedc3821d34f8d4/Samples/App.xaml#L69
的提示
似乎只能使用原生样式

**Comment by Mochengvia** [comment]
PendingBox默认使用额外的STA线程来创建并打开窗体。
你可以通过将PendingBoxSettings.Setting.CreateNewThread属性设置为False来使用自定义样式。但如果当前UI线程正在执行渲染等耗时操作，PendingBox的旋转控件会被卡住。
或者，你也可以选择在CancelButtonStyle中直接编写Style和Template。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月6日(周一) 下午4:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PanuonGroup/Panuon.WPF.UI] 在PendingBoxSettings.CancelButtonStyle使用StaticResource时提示无法序列化非公共类型 (Issue #147)




 
以下方法在MessageBoxXSettings中适用,但在PendingBoxSettings中无法使用
 <pu:PendingBoxSettings   x:Key="pendingSettings"   CancelButtonStyle="{StaticResource ButtonBaseStyle}"&gt; </pu:PendingBoxSettings&gt;
 <pu:PendingBoxSettings.ContentTemplate&gt;   <DataTemplate&gt;     <Grid&gt;       ...       <Button         x:Name="PART_CancelButton"         Grid.Row="3"         Margin="0,5,0,0"         Style="{StaticResource ButtonBaseStyle}"         HorizontalAlignment="Center"         Visibility="Collapsed" /&gt;     </Grid&gt;   </DataTemplate&gt; </pu:PendingBoxSettings.ContentTemplate&gt;
 <pu:PendingBoxSettings.CancelButtonStyle&gt;   <Style BasedOn="{StaticResource ButtonBaseStyle}" TargetType="Button" /&gt; </pu:PendingBoxSettings.CancelButtonStyle&gt;
 
 
完整错误信息
 System.InvalidOperationException   HResult=0x80131509   Message=无法序列化非公共类型“Panuon.WPF.UI.Internal.Converters.IsNonnullConverter”。   Source=PresentationFramework   StackTrace:    在 System.Windows.Markup.Primitives.MarkupWriter.VerifyTypeIsSerializable(Type type)    在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)    在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)    在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)    在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)    在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)    在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)    在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)    在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)    在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)    在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)    在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item, Scope scope)    在 System.Windows.Markup.Primitives.MarkupWriter.WriteItem(MarkupObject item)    在 System.Windows.Markup.Primitives.MarkupWriter.SaveAsXml(XmlWriter writer, MarkupObject item)    在 System.Windows.Markup.Primitives.MarkupWriter.SaveAsXml(XmlWriter writer, Object instance, XamlDesignerSerializationManager manager)    在 System.Windows.Markup.XamlWriter.Save(Object obj, XamlDesignerSerializationManager manager)    在 Panuon.WPF.UI.Internal.Utils.XamlUtil.ToXaml[T](T obj)    在 Panuon.WPF.UI.PendingBox.<&gt;c__DisplayClass21_0.<CallPendingBox&gt;b__0()    在 System.Windows.Threading.Dispatcher.Invoke[TResult](Func`1 callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)    在 Panuon.WPF.UI.PendingBox.Show(String message)    在 StarsectorTools.Views.MainWindow.MainWindow.<Button_TitleMin_Click&gt;d__18.MoveNext() 在     StarsectorTools\Views\MainWindow\MainWindow.xaml.cs 中: 第 81 行

**Comment by Hakoyu** [comment]
有大量的渲染任务确实会出现卡住的问题
那我选择后者,尽管不能使用`Helpers`会让`CancelButton`和其它`Button`看起来有些不一样
