### ISSUE TITLE
1.1.8.4更新后导致DataGrid滚动从一项变成了一页

### ISSUE THREAD

**Issue by Hakoyu** [PanuonGroup/Panuon.WPF.UI#151]
# 1.1.8.2
![Honeycam 2023-03-13 19-30-14](https://user-images.githubusercontent.com/48956359/224690090-ae24bb86-945f-44de-95a5-274d48cb8585.gif)

# 1.1.8.4
![Honeycam 2023-03-13 19-31-56](https://user-images.githubusercontent.com/48956359/224690109-7c9ca037-1dbe-4a86-966c-ca886592b347.gif)

**Comment by Mochengvia** [comment]
经过确认，此问题将在1.1.8.5版本中修复，请留意版本更新

**Comment by Hakoyu** [comment]
1.1.8.5+ 并没有修复 使用滚轮滚动时依旧时滚动一整页

**Comment by Mochengvia** [comment]
我在1.1.8.5版本测试了你的代码，问题没有复现。 
![anima](https://user-images.githubusercontent.com/23360265/231728417-1cb9b663-fd4f-464f-98ef-53123e0445a9.gif)
![图片](https://user-images.githubusercontent.com/23360265/231728471-3b16b2a4-b59f-41ed-bbc0-a44bd102a678.png)

**Comment by Hakoyu** [comment]
怪事 我怎么就没修复呢

![Honeycam 2023-04-13 18-43-09](https://user-images.githubusercontent.com/48956359/231735540-cf3c5dd4-aed9-43de-a0cf-8ed6285cf14c.gif)

![Honeycam 2023-04-13 18-44-23](https://user-images.githubusercontent.com/48956359/231735515-42504ca4-f50a-4c3f-8b49-a5bf09c49b71.gif)

**Comment by Mochengvia** [comment]
看起来是ScrollViewer导致的问题，我再研究一下

**Comment by Mochengvia** [comment]
我似乎找到了一个最终方法来解决这个问题，请等待下个版本的更新

**Comment by Hakoyu** [comment]
好的 期待更新

**Comment by Hakoyu** [comment]
经测试 在 **1.1.9.4** 中修复
