### ISSUE TITLE
引用 这个资源后， Menu 不会显示

### ISSUE THREAD

**Issue by heartacker** [PanuonGroup/Panuon.WPF.UI#155]
- 在APP 中注释
```
 <!--<ResourceDictionary Source="pack://application:,,,/Panuon.WPF.UI;component/Control.xaml"/>-->
```
![image](https://user-images.githubusercontent.com/1876302/227778084-901db83b-5dc2-4a85-88e3-d485079f0bba.png)

- 在APP 中添加
```
 <ResourceDictionary Source="pack://application:,,,/Panuon.WPF.UI;component/Control.xaml"/>
```
![image](https://user-images.githubusercontent.com/1876302/227778122-eabdf5a7-cb3d-4677-a5b1-ff8ac83bf671.png)

**Comment by Mochengvia** [comment]
收到 明天我检查一下代码



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月26日(周日) 晚上9:14
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PanuonGroup/Panuon.WPF.UI] 引用 这个资源后， Menu 不会显示 (Issue #155)




  
在APP 中注释
   <!--<ResourceDictionary Source="pack://application:,,,/Panuon.WPF.UI;component/Control.xaml"/&gt;--&gt;  

  
在APP 中添加
   <ResourceDictionary Source="pack://application:,,,/Panuon.WPF.UI;component/Control.xaml"/&gt;

**Comment by heartacker** [comment]
我也安装了 handycontrol 这个包，
我发现禁用他的这个也可以正常显示。
所以这两个包应该是冲突了，但是我我不知道如何处理
![image](https://user-images.githubusercontent.com/1876302/227782595-ae666a4f-6fe3-44d2-a0e0-516e4869b672.png)

**Comment by Mochengvia** [comment]
试试在Menu上加上这个：
```
Style="{StaticResource {x:Static purs:StyleKeys.MenuStyle}"
```

这可以强制将样式设置为pu的样式
