### ISSUE TITLE
应用这个资源后， combox item不显示

### ISSUE THREAD

**Issue by heartacker** [PanuonGroup/Panuon.WPF.UI#156]
本次只有一个资源，已经排除了其他资源

<ResourceDictionary Source="pack://application:,,,/Panuon.WPF.UI;component/Control.xaml"/>

1. 异常情况

![image](https://user-images.githubusercontent.com/1876302/228467621-fc09b1dc-7295-425d-a9e2-af5f6a9337eb.png)

2. 正常
![image](https://user-images.githubusercontent.com/1876302/228467260-8680ba27-cc61-45c8-addf-15881c7eee6a.png)

**Comment by Mochengvia** [comment]
应用哪个资源？在issue中附上代码

**Comment by heartacker** [comment]
![Uploading image.png…]()

**Comment by Mochengvia** [comment]
我新建了一个项目并测试了ComboBox控件，在1.1.8.5版本中没有复现你提到的问题。
如果你能提供更多的代码或能够复现的项目，请留言。

**Comment by Mochengvia** [comment]
另外，你图中的ComboBox并非pu中提供的ComboBox样式。如果你是在ComboBox中为ComboBoxItem应用了样式，在ComboBox没有应用样式的前提下，它们不会生效。
