### ISSUE TITLE
应用PU 资源后，listview 不显示

### ISSUE THREAD

**Issue by heartacker** [PanuonGroup/Panuon.WPF.UI#157]
如图，注释之后就显示了
![rss](https://user-images.githubusercontent.com/1876302/228785179-5ed440d1-37a4-4718-9791-1921b0ff1bcc.gif)

**Comment by heartacker** [comment]
<Style BasedOn="{x:Null}" TargetType="ListViewItem"/>
在app.xaml 中设置这个也可以恢复

**Comment by Mochengvia** [comment]
此问题已在1.11以上的版本中修复
