### ISSUE TITLE
1.1.9 更新后 导致 Expander 内嵌的 ListBox 宽度被锁定

### ISSUE THREAD

**Issue by Hakoyu** [PanuonGroup/Panuon.WPF.UI#159]
# 1.1.8.5
![Honeycam 2023-04-06 22-13-56](https://user-images.githubusercontent.com/48956359/230404771-8d3d2b24-780b-4278-978e-f90db55c1de6.gif)

# 1.1.9
![Honeycam 2023-04-06 22-10-54](https://user-images.githubusercontent.com/48956359/230404919-c381b177-7e05-49ed-b0ff-f15a458b3b78.gif)

**Comment by Mochengvia** [comment]
能提供一个复现的控件结构吗？我没有看懂这个错误是什么



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月6日(周四) 晚上10:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PanuonGroup/Panuon.WPF.UI] 1.1.9 更新后 导致 Expander 内嵌的 ListBox 宽度被锁定 (Issue #159)




 
1.1.8.5
 

 
1.1.9

**Comment by Mochengvia** [comment]
啊 我好像明白你的意思了 明天我看一下

**Comment by Hakoyu** [comment]
结构是
```xaml
<Grid>
  <StackPanel>
    <ListBox/>
    <Expander>
      <ListBox/>
    </Expander>
    <Expander>
      <ListBox/>
    </Expander>
  <StackPanel>
</Grid>
```
通过设置 `Grid` 的宽度 来控制整个结构的宽度
如果默认 `Grid` 宽度设置为 `NaN`
就可以正常使用

但如果默认为 `30`
再修改为 `NaN` 时
就无法改变 `Expander` 内 `ListBox`的宽度

也许是虚拟化相关的问题 ?

**Comment by Mochengvia** [comment]
我发布了新的版本1.1.9.1，请更新到最新版本，然后再试一次。

**Comment by Hakoyu** [comment]
经测试 此问题已修复
