### ISSUE TITLE
NoticeBox会显示到主窗体后边

### ISSUE THREAD

**Issue by jiushi97** [PanuonGroup/Panuon.WPF.UI#54]
运行弹出窗口或者切换主窗体后，之后的NoticeBox都会显示到主窗体后边，看不到。

**Comment by Mochengvia** [comment]
感谢反馈
在调用NoticeBox.Show方法时，将第一个owner参数指定为当前主窗体可以解决这个问题。
如果已经指定，请提供能复现此问题的测试项目或代码。

**Comment by jiushi97** [comment]
![image](https://user-images.githubusercontent.com/32998467/160315188-5edc1d4f-141d-428a-b07a-d56b5a22378a.png)
没有owner参数啊？用的.net6

**Comment by jiushi97** [comment]
需要修改源代码Panuon.UI.Silver下的Helpers文件夹下的NoticeBox.cs  ， 实例化的时候加上 Owner=Application.Current.MainWindow。
修改后为_noticeWindow = new NoticeBoxWindow(animationEase, animationDuration) { Owner=Application.Current.MainWindow};即可。

**Comment by jiushi97** [comment]
需要修改源代码Panuon.UI.Silver下的Helpers文件夹下的NoticeBox.cs  ， 实例化的时候加上 Owner=Application.Current.MainWindow。
修改后为_noticeWindow = new NoticeBoxWindow(animationEase, animationDuration) { Owner=Application.Current.MainWindow};即可。

**Comment by Mochengvia** [comment]
NoticeBox允许使用一个单独的线程启动，所以将Owner设置为MainWindow并不是通用的做法。
有关NoticeBox会显示在后边的问题，已经在2.2.19版本中修复，更新版本后仍会出现此问题吗？

**Comment by jiushi97** [comment]
会，先弹出一下，然后最小化主窗体，再最大化，再弹出就显示到主窗体后边了。

**Comment by Mochengvia** [comment]
根据最新的确认，在Net Core（包括3.1, 5, 6）中会存在NoticeBox无法置顶的问题。
这个问题是由于新开UI线程中的窗体，无法通过设置Topmost属性或调用SetWindowPos方法置顶导致的，暂时没有找到解决方案。
如有必要，为了解决这个问题，请参照wiki文档中的方法将CreateOnNewThread属性设置为False。这可以解决无法置顶的问题，但NoticeBox将在当前UI线程中启动。如果程序退出时进程没有结束（比如App中ShutdownMode为OnLastWindowClosed），则需要在程序准备退出时手动调用NoticeBox.DestroyInstance()方法来释放实例。
如果之后的版本中找到了解决方案，我会在此留言。

**Comment by Mochengvia** [comment]
抱歉，我以为是PendingBox，我研究下代码



------------------ 原始邮件 ------------------
发件人: jiushi97 ***@***.***&gt;
发送时间: 2022年3月28日 10:16
收件人: Panuon/Panuon.UI.Silver ***@***.***&gt;
抄送: 末城via ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Panuon/Panuon.UI.Silver] NoticeBox会显示到主窗体后边 (Issue #54)





 

 没有owner参数啊？用的.net6
