### ISSUE TITLE
2.2.18版本中已知的问题

### ISSUE THREAD

**Issue by Mochengvia** [PanuonGroup/Panuon.WPF.UI#56]
这些问题将在2.2.19版本中修复。  

- FormGroup在Vertical状态下没有水平铺满。
- ProgressBar存在绑定错误问题。
- CacheControl存在布局测量错误，内部控件不会显示滚动条。
- DateTimePicker的MinDateTime和MaxDateTime在一些场景下无法限制时间选择。
- SearchBox控件重做
- ScrollBarHelper.ThumbCornerRadius属性无法从父控件上继承。

**Comment by BruceHao** [comment]
1. 日历显示与实际星期不匹配.
