### ISSUE TITLE
Switch控件不可用

### ISSUE THREAD

**Issue by efojug** [PanuonGroup/Panuon.WPF.UI#60]
pu:Switch无法通过代码设置开启/关闭，且开发文档内缺少这一部分的描述

**Comment by Mochengvia** [comment]
抱歉，我无法从你的描述中复现此问题。
Switch继承自ToggleButton，可以使用IsChecked属性来调整开关。
如果能提供可以复现的代码或项目，请在此留言。

**Comment by Mochengvia** [comment]
如果仍有问题，请重新打开此issue。
