### ISSUE TITLE
TabControl  ItemRemoved不可用

### ISSUE THREAD

**Issue by wzhan1988** [PanuonGroup/Panuon.WPF.UI#72]
Panuon.WPF.UI.TabControlHelper.ItemRemoved=“TabControl_ItemRemoved”无效。“ItemRemoved”必须是使用以关键字“Event”结束的名称注册的 RoutedEvent。

**Comment by Mochengvia** [comment]
此问题已确认，最迟将于明天发布新的补丁包。

**Comment by Mochengvia** [comment]
此问题已经在1.0.5版本中修复。
如果仍有问题，请重新打开此issue。
