### ISSUE TITLE
ListView 行高无法自适应

### ISSUE THREAD

**Issue by jiushi97** [PanuonGroup/Panuon.WPF.UI#73]
ItemsPanelTemplate设为WrapPanel，高度不能自适应，会截断

**Comment by jiushi97** [comment]
源码中<Setter Property="local:ListViewHelper.ItemsHeight"
                Value="35" /> 是否可以改成ItemsMinHeight

**Comment by Mochengvia** [comment]
ListViewHelper中已经存在ItemsMinHeight、ItemsHeight和ItemsMaxHeight属性。
需要实现什么效果？

**Comment by Mochengvia** [comment]
如果仍有问题，请重新打开此issue。
