### ISSUE TITLE
窗体最大化后，任务栏遮挡3个像素

### ISSUE THREAD

**Issue by Dstary** [PanuonGroup/Panuon.WPF.UI#80]
![image](https://user-images.githubusercontent.com/41058811/183554808-820c8bc8-1d5c-436a-a6c9-c811053b431a.png)
![image](https://user-images.githubusercontent.com/41058811/183554861-01deaa62-4860-41cc-a97d-2ffa9bf0b334.png)
通过对比图片可以看到左下角红色底部不见了

**Comment by Mochengvia** [comment]
感谢反馈。
此问题已经复现，下个版本将修复此问题。

**Comment by Mochengvia** [comment]
此问题已在1.0.6中修复。如果仍有问题，请重新打开此issue。
