### ISSUE TITLE
ProgressBar没有循环的运动的动画了

### ISSUE THREAD

**Issue by Dstary** [PanuonGroup/Panuon.WPF.UI#83]
IsIndeterminate="True"这个设置后不起作用

**Comment by Mochengvia** [comment]
感谢反馈。
已记录，这个问题会在下个版本解决


------------------ 原始邮件 ------------------
发件人: Dstary ***@***.***&gt;
发送时间: 2022年8月12日 22:29
收件人: PanuonGroup/Panuon.WPF.UI ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [PanuonGroup/Panuon.WPF.UI] ProgressBar没有循环的运动的动画了 (Issue #83)





 
IsIndeterminate="True"这个设置后不起作用

**Comment by Mochengvia** [comment]
此问题已在1.1.1中修复。
如果仍有问题，请重新打开此issue。
