### ISSUE TITLE
设置全屏和 WindowStyle.None后，还是有边框

### ISSUE THREAD

**Issue by TzBluesky28** [PanuonGroup/Panuon.WPF.UI#84]
设置全屏和 WindowStyle.None后，还是有边框的标题栏出现

**Comment by jiushi97** [comment]
设置pu:WindowXCaption.Background="Transparent" 即可

**Comment by Mochengvia** [comment]
WindowStyle对WindowX暂时没有效果。要隐藏标题栏，请使用pu:WindowXCaption.Height="0"。
如果有其他问题，请重新打开此issue。
