### ISSUE TITLE
PasswordBoxHelper.Password 绑定中使用ValidationRules，错误不会消失。

### ISSUE THREAD

**Issue by jiushi97** [PanuonGroup/Panuon.WPF.UI#90]
<pu:FormGroup Header="{StaticResource lblOldPassword}">
                <PasswordBox Name="PwdOld" MaxLength="20" Width="220">
                    <pu:PasswordBoxHelper.Password>
                        <Binding Path="Password.Old" Mode="TwoWay"  UpdateSourceTrigger="PropertyChanged">
                            <Binding.ValidationRules>
                                <rules:NotNullValidationRule ValidatesOnTargetUpdated="True" />
                            </Binding.ValidationRules>
                        </Binding>
                    </pu:PasswordBoxHelper.Password>
                </PasswordBox>
</pu:FormGroup>

**Comment by Mochengvia** [comment]
FormGroup暂未支持ValidationRules

**Comment by jiushi97** [comment]
![image](https://user-images.githubusercontent.com/32998467/188053657-091a7afd-5889-4fb4-9883-d1a9b5cd90a7.png)
有bug，编辑后显示不全了。
加上 pu:PasswordBoxHelper.PasswordHook="True" 这个就正常了。。是我疏忽了。
