### ISSUE TITLE
窗体缩小过一次后DropDown没反应了。

### ISSUE THREAD

**Issue by jiushi97** [PanuonGroup/Panuon.WPF.UI#97]
`<pu:DropDown pu:DropDownHelper.Placement="Bottom"
                     Margin="0 0 20 0"
                     Background="Transparent"
                     StaysOpen="True">
            <pu:DropDown.Style>
                <Style TargetType="pu:DropDown">
                    <Style.Triggers>
                        <Trigger Property="IsMouseOver" Value="True">
                            <Setter Property="IsOpen" Value="True" />
                        </Trigger>
                        <Trigger Property="IsMouseDirectlyOver" Value="True">
                            <Setter Property="IsOpen" Value="True" />
                        </Trigger>
                    </Style.Triggers>
                </Style>
            </pu:DropDown.Style>
            <pu:DropDown.Content>
                <StackPanel Orientation="Horizontal" Height="62">
                    <TextBlock Text="{Binding CurrentUser.name}" />
                    <TextBlock Text="&#xf107;" />
                </StackPanel>
            </pu:DropDown.Content>
            <StackPanel>
                <Button Style="{StaticResource LinkBtn}" Content="{StaticResource lblChangePassword}" pu:ButtonHelper.HoverForeground="{DynamicResource Primary}" Tag="Account/Pwd" Click="Button_Click"  />
                <Button Name="BtnLogOut" Style="{StaticResource LinkBtn}" Content="{StaticResource lblLogOut}" pu:ButtonHelper.HoverForeground="{DynamicResource Primary}" Click="BtnLogOut_Click" />
            </StackPanel>
        </pu:DropDown>`

**Comment by Mochengvia** [comment]
务必参照Samples中的登录界面示例来使用DropDown。
你需要在Content中放置一个ToggleButton。
